# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa62f01a20c1b3d8f28d1e5e2222b3a747288dd9fd169954480cdeb168a5a3ad22899560a5d5749cf67279c976d91fcbb97977ce87ba3ddea943f581544d530

test:
  secret_key_base: 1f611f6ac529f3ca822ef0dca658bda891630c1c10687640f065794f0e223c642591e73905bb276684fad1bbc60bdaf9ae2e6309610a570466d9466ec6e36823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
